### ISSUE TITLE
Allow configuration of OSQuery

### ISSUE THREAD

**Issue by andrewhowdencom** [kbrebanov/ansible-osquery#2]
Hola, 

I think OSQuery uses JSON to configure it's behaviour. Would you be happy getting a PR that allowed configuring it by specifying its full configuration tree in yaml, and using the toJson filter of Ansible to render it to it's final format?

I think this is more flexible and lower overhead than allowing a set of specific configuration options.

**Comment by andrewhowdencom** [comment]
Also asked in https://github.com/ssummer3/ansible-osquery/issues/3

**Comment by kbrebanov** [comment]
This Ansible role is no longer being maintained.
